from collections import Counter

def get_num_words(filepath):

    try:
        with open(filepath) as f:
            file_contents = f.read()
            #print(file_contents)
            wordsplit = file_contents.split()
            result = (len(wordsplit))
    except Exception as e:
        result = e
    return result

## Get book text
def get_book(filePath: str) -> str:
    try:
        with open(filePath) as f:
            file_contents = f.read()
            result = file_contents
    except Exception as e:
        result = e
    return result

## Split strings
def count_letters(readString: str) -> dict[str, int]:
    result: dict[str, int] = {}  

    for lett in readString:
        letter = lett.lower()
        if lett in result:
           result[letter] += 1
        else:
            result[letter] = 1

    return result

## Generated by AI, what is diffrent?
def count_letters_ai(readString: str) -> dict[str, int]:
    result: dict[str, int] = {}

    for char in readString:
        key = char.lower()          # compute once
        if key in result:
            result[key] += 1        # shorthand for result[key] = result[key] + 1
        else:
            result[key] = 1

    return result


def count_letters2(readString: str) -> dict[str, int]:
    return dict(Counter(readString.lower()))